{% set name = "flake8-to-ruff" %}
{% set version = "0.0.234" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8_to_ruff-{{ version }}.tar.gz
  sha256: 00f1eb4115523f28d9cabaa06c26ee88ea68d1193b1a09209bac9d30949a8b22

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - maturin >=0.14,<0.15
    - pip
  run:
    - python

test:
  commands:
    - flake8-to-ruff --help

about:
  home: https://github.com/charliermarsh/ruff#subdirectory=crates/flake8_to_ruff
  summary: Convert existing Flake8 configuration to Ruff.
  license: MIT
  license_file: local_dependencies/ruff/LICENSE

extra:
  recipe-maintainers:
    - svengiegerich
